version: "3.9"
services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DBHOST=${DBHOST}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
